[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_dev_workshop = "8Pf8RCh4hEHqe9uVtVqs6SnytqfdmY3z28ky8A7JKDUQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ascespool/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
